# Generated by Django 4.2.1 on 2023-06-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_framework_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.framework')),
            ],
        ),
    ]
