# Generated by Django 4.2.1 on 2023-06-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='first_app.framework'),
        ),
    ]
