# Generated by Django 4.2.1 on 2023-06-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_category_order_product_orderitem_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='framework',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='first_app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='first_app.category'),
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
