# Generated by Django 4.2.1 on 2023-07-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='first_app.order'),
        ),
    ]
