# Generated by Django 4.2.1 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_rating_order_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='incoming_rating',
            field=models.FloatField(default=0),
        ),
    ]
