# Generated by Django 4.2.1 on 2023-07-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_remove_product_incoming_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itotal_rating_sum',
            new_name='total_rating_sum',
        ),
    ]
